
name: devolop_workspace
repository: https://github.com/darolishes/DevolopWorkspace

packages:
  - packages/*
  - packages/*/*
  - packages/*/*/*
  - tests

command:
  bootstrap:
    runPubGetInParallel: true

scripts:
  lint:
    run: flutter analyze .
    description: Führen Sie statische Analyseprüfungen aus.

  test:
    run: flutter test
    description: Führen Sie Flutter-Tests aus.

  build:
    run: flutter build
    description: Führen Sie den Flutter-Buildprozess aus.

  format:
    run: flutter format .
    description: Formatieren Sie den Code.

  clean:
    run: flutter clean
    description: Bereinigen Sie das Build-Verzeichnis.

  pub_get:
    run: melos run pub get
    description: Führen Sie "pub get" für alle Pakete aus.

  coverage:
    run: flutter test --coverage
    description: Generieren Sie Codeabdeckungsberichte.

  pre_commit:
    run: melos run lint && melos run test && melos run format
    description: Führen Sie alle notwendigen Checks vor einem Commit aus.
