name: devolop_project_management
description: CRUD-Operationen für Projekte in Devolop
version: 0.0.1
publish_to: none

environment:
  sdk: "^3.1.0"

dependencies:
  core:
    path: ../devolop_core
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter