name: auth
description: Authentication mechanisms for DevManagementPlatform.
version: 0.0.1
publish_to: none

environment:
  sdk: "^3.1.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  firebase_auth: ^4.10.1
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.auth
        pluginClass: AuthPlugin
      ios:
        pluginClass: AuthPlugin

# Exporting variables and functionalities as per the plan
export:
  - lib/services/auth_service.dart
