name: devolop_auth
description: Authentifizierung und Autorisierung für Devolop.
version: 0.0.1

publish_to: none

environment:
  sdk: "^3.1.0"

dependencies:
  core:
    path: ../devolop_core
  flutter:
    sdk: flutter
  firebase_auth: ^4.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
