name: ui
description: Flutter-based User Interface for DevManagementPlatform.
version: 0.0.1

publish_to: none

environment:
  sdk: "^3.1.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  riverpod: ^2.4.3
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.ui
        pluginClass: UiPlugin
      ios:
        pluginClass: UiPlugin

# Exporting variables and functionalities as per the plan
export:
  - lib/widgets/project_widget.dart
  - lib/widgets/server_widget.dart
  - lib/widgets/environment_widget.dart
