name: env_management
description: Environment management tools and services for DevManagementPlatform.
version: 0.0.1
publish_to: none

environment:
  sdk: "^3.1.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  dotenv: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
